export const QUEUE_CONFIG = {
  POLLING_INTERVAL_MS: 5000,
  SOUND_FREQUENCY_HIGH_HZ: 800,
  SOUND_FREQUENCY_LOW_HZ: 600,
  SOUND_DURATION_FIRST_TONE_MS: 300,
  SOUND_DURATION_SECOND_TONE_MS: 600,
  SOUND_VOLUME: 0.3,
  CARD_MIN_HEIGHT_PX: 400,
  TICKET_ID_PADDING_LENGTH: 4,
  MAX_VISIBLE_DOCTORS: 6
};

